name: Deploy to Server

on:
  push:
  pull_request:

jobs:
  markdownlint:
    name: markdownlint-cli2-action
    uses: DavidAnson/markdownlint-cli2-action@v20.0.0
    with:
      globs: |
        'source/organize/**/*.md'
        'source/textbook/**/*.md'
