name: Deploy to Server

on:
  push:
  pull_request:

jobs:
  markdownlint:
    name: markdownlint-cli2-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: |
            source/organize/**/*.md
            source/textbook/**/*.md
          fix: true
